spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=shop
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://shop
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/shop/**

spring.cloud.gateway.server.webmvc.routes[2].id=admin
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://admin
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/admin/**
